sudo: required
language: node_js
node_js: '8'
git:
  depth: 1
cache:
  yarn: true
  directories:
  - che-theia-java-extension/node_modules
branches:
  only:
  - master
env:
  global:
    - NODE_OPTIONS="--max_old_space_size=4096"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0
  - export PATH=$HOME/.yarn/bin:$PATH ;
install: yarn install
script: skip
jobs:
  fast_finish: true
  include:
  - stage: deploy
    os: linux
    before_deploy:
      - printf "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}\n" >> ~/.npmrc
    deploy:
      - provider: script
        script: cd che-theia-java-extension && npm version -no-git-tag-version "0.0.1-$(date +%s)" && npm publish --access public
        on:
          branch: master
        skip_cleanup: true
      - provider: script
        script: cd che-theia-java-extension && npm version -no-git-tag-version && npm publish --access public
        on:
          tags: true
        skip_cleanup: true
